name: xRpg
version: '0.1-ALPHA'
main: me.chancy.xRpg.XRpg
api-version: '1.21'
authors: [ Chancy ]
description: Rpg plugin
commands:
  xrpg:
    description: XRpg management commands
    usage: /xrpg give <block>